name: Docker compilation pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-tast-container:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v4

      - name: Compile application image
        run: |
          echo "Commencing automated docker build sequence"
          docker build -t test-automation-image:latest .
          echo "Container image compiled successfully with zero errors."
